'superlist_runtests':
    script:
        - "sudo pip3 install virtualenv"
        - rm -rf ../database
        - mkdir -p ../database
        - mkdir -p ../virtualenv
        - "cd .. && virtualenv --python=python3 virtualenv"
        - "virtualenv/bin/pip install -r superlist/requirements.txt"
        - "virtualenv/bin/pip install selenium"
        - "cd superlist && ../virtualenv/bin/python3 manage.py migrate --noinput"
        - "../virtualenv/bin/python3 manage.py test --verbosity=1 --settings=superlists.settings.test"
    tags:
    except:
        - tags
